#!/bin/bash

################################################################################
# TOAD Extrude
#
# Extrudes a tileset (metatask)
################################################################################

src=$1
out=$2
tw=32
th=32
margin=0
spacing=0
border=2
anchor="tl"

# Collect arguments
while [ $# -gt 0 ]; do
	case "$1" in
		-src|-tileset)
			shift
			src=$1
			;;
		-o|-out)
			shift
			out=$2
			;;
		-b|-border)
			shift
			border=$1
			;;
		-tw|-tilewidth)
			shift
			tw=$1
			;;
		-th|-tileheight)
			shift
			th=$1
			;;
		-size|-tilesize)
			shift
			size="${1}x"
			tw=`echo "$size" | cut -dx -f1`
			th=`echo "$size" | cut -dx -f2`
			;;
		-m|-margin)
			shift
			margin=$1
			;;
		-s|-spacing)
			shift
			spacing=$1
			;;
		-a|-anchor)
			shift
			anchor=$1
			;;
		-*)
			echo "Unknown option '${1}' (ignoring)"
			shift
			;;
		*)
			[ "$1" != "" ] && out=$1
			;;
	esac
	shift
done

# Do error checks
if [ "$src" = "" ]; then
	echo "No source image provided"
	exit 1
fi

if [ `test -e $src` ]; then
	echo "No file $src"
	exit 1
fi

if [ "$out" = "" ]; then
	echo "No extruded image name provided"
	exit 1
fi

srcname=${src##*/}
srcname=${srcname%%.*}

size=`$MAGICK_CONVERT $src -ping -format "%wx%h" info: 2>>$TOAD_ERROR_LOG`
imgw=`echo "$size" | cut -dx -f1`
imgh=`echo "$size" | cut -dx -f2`
fitw=$(($tw+$spacing))
fith=$(($th+$spacing))
ntx=$(($imgw/$fitw))
nty=$(($imgh/$fith))

$TOAD_EXTRACT $src -f tmp_extracted_extrude_$srcname -tw $tw -th $th -m $margin -s $spacing

$TOAD_LOG "Extruding tiles..."
for tileimg in tmp_extracted_extrude_$srcname/*; do
	$TOAD_EXTRUDEIMG $tileimg -b $border -out $tileimg -a $anchor
done

$TOAD_PACK tmp_extracted_extrude_$srcname $out -m $margin -s $spacing -tw $(($tw+$border*2)) -th $(($th+$border*2)) -d ${ntx}x${nty}

rm -f tmp_extracted_extrude_$srcname/*
rmdir tmp_extracted_extrude_$srcname